services:
  - type: web
    name: my-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn backend:app --bind 0.0.0.0:10000"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
        
    
